### ISSUE TITLE
IOS method call make app crash

### ISSUE THREAD

**Issue by yesiman** [yesiman/ekoal.cdv.sumup#2]
sur iOS et j'ai une erreur qui s'affiche dans xCode quand je veux executer ma method pay, te souviens tu avoir fait quelque chose en particulier ? Je ne connais pas du tout l'environnement de dev d'apple donc c'est embetant pour modifier des trucs.

**Comment by epicazo** [comment]
```
-[__NSCFNumber length]: unrecognized selector sent to instance 0x14dc85f0

*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSCFNumber length]: unrecognized selector sent to instance 0x14dc85f0
```

J'ai ça comme erreur dans la console xCode quand j'appel la fonction pay, à savoir que j'ai gardé les fichiers CDVSumup.h  CDVSumup.m mais que j'ai changé le SumupSDK.embeddedframework par celui qui est dispo sur le github de Sumup (2.3)

**Comment by yesiman** [comment]
Tu peux faire un test tout simple ? Modifie le nom de la méthode pay dans le JS par un autre nom, si l'erreur est la meme c'est que l'appel js ne trouve pas le namespace du plugin, sans doute une config a ajouté dans le package json peux tu tester ? merci.

**Comment by OliverTr54** [comment]
Could you translate this into english? Please...

**Comment by epicazo** [comment]
@OliverTr54 I copy paste the error I have in my XCode when I try to execute the pay method, I have the same error using the sdk provided in the cordova plugin and the 2.3.0.

@yesiman I tried to change the name but the error I got was that the sumup plugin didn't reconnize it : 
```
ERROR: Method 'payment:' not defined in Plugin 'Sumup'
[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["Sumup618811497","Sumup","payment",[10,"EUR"]]
```

**Comment by yesiman** [comment]
Ok if the change cause this time method unrecognison it's a method change in the new SDK then it is very easy to resolve, if i have a time i will compare 1.55 vs 2* SumUP sdk

**Comment by yesiman** [comment]
@OliverTr54 `<NSInvalidArgumentException> -[__NSCFNumber length]` perhaps you send integer amount instead of decimal.
Check your currency code too.
If needed hardcode values.

**Comment by epicazo** [comment]
I tried some stuff today, seems that the error i was getting on the pay method was because it doesn't convert the amount in string so i hardcoded it and it throw me an error from sumup saying i'm not logged in, and I've been looking into the log method without making it work this is the error i'm getting : 

` *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/D099C14B-65C3-4E9B-B63F-BB1872CE35F2/SUMUP.app> (loaded)' with name 'SMPSDKWelcomeViewController''`

And from what I tested, the difference from the iOS SDK on the github page and what you've provided is SumupSDK presentLoginFromViewController:**self.viewController**

**Comment by yesiman** [comment]
As explained in sum sdk documentation and in my previous post the amount should be a decimal so you have to pass a decimal from your application to the method. The conversion si ok (JS) your source value has tobe ok.

For the login method it seems that sumip sdk is not fully installed beacause a view is missing. This error is not from the plugin itself.

**Comment by epicazo** [comment]
The login method crash the app because apparently the bundle isn't properly imported... see : https://github.com/sumup/sumup-ios-sdk/issues/18

I followed the steps here : https://github.com/sumup/sumup-ios-sdk#preparing-your-xcode-project 
and checked that the files were correctly imported and it seems that they are 
![capture d ecran 2017-07-13 a 14 46 22](https://user-images.githubusercontent.com/8203618/28166809-b34d9b02-67d9-11e7-8f69-7cb15b6b31a9.png)


I don't know what else to do :/

**Comment by yesiman** [comment]
I think than now you have to follow SumUP  SDK documentation it's not a plugin issue.
